default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_exam1_development

test:
  <<: *default
  database: rails_exam1_test

production:
  <<: *default
  database: rails_exam1_production
  username: rails_exam1
  password: <%= ENV['RAILS_EXAM1_DATABASE_PASSWORD'] %>
